apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  selector:
    matchLabels:
      app: java
  replicas: 2
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/hello-world:java
        ports:
        - containerPort: 8080 
